name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install yarn
        run: sudo apt update && sudo apt install yarn

      - name: Install Dependencies
        run: yarn install

      - name: Jest Unit Test & Linting
        run: yarn test

      - name: Build
        run: yarn build